
---
sudo: false
language: c
compiler:
  - clang

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - make test

branches:
  only:
   - nw_algo

addons:
  apt:
    packages:
      - gcc-multilib
