#!/bin/bash

TOTAL=0
FAIL=0
PERCENT=0.00

while [ $TOTAL -lt 1000 ]
do
	./fillit ../test/test/valid_$1 > ../test/out/$1.out
	sleep 0.1
	((TOTAL++))
	if ! diff ../test/out/$1.out ../test/valid/output_valid_$1 > /dev/null; then
		((FAIL++))
	fi
#	printf "\e[1;1H"
#	printf "\e[32mTotal \e[0m: \e[36m$TOTAL\e[0m\n\e[31mFail  \e[0m: \e[36m$FAIL \e[33m($(awk "BEGIN {print $FAIL/($TOTAL/100)}")%%)                 \e[0m"
done
printf "\n\n- File:$1 -\nTotal : $TOTAL\nFail  : $FAIL ($(awk "BEGIN {print $FAIL/($TOTAL/100)}")%%)\n"
